import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="sticky top-0 z-10 bg-white shadow-sm border-b border-gray-200">
          <nav className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
            <div className="text-2xl font-bold text-gray-800">Blog App</div>
            <div className="flex gap-8">
              <Link href="/" className="text-gray-600 hover:text-indigo-600 font-medium transition">
                Home
              </Link>
              <Link href="/about" className="text-gray-600 hover:text-indigo-600 font-medium transition">
                About
              </Link>
              <Link href="/blog" className="text-gray-600 hover:text-indigo-600 font-medium transition">
                Blog
              </Link>
            </div>
          </nav>
        </header>
      <main className="flex-grow">{children}</main>

        <footer className="bg-gray-100 border-t border-gray-200 py-8">
          <div className="max-w-7xl mx-auto px-6 text-center text-gray-600">
            © 2025 Blog App
          </div>
        </footer>
      </body>
    </html>
  );
}
